[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/alacritty"
hook = "cp -f %f ~/.config/alacritty/colors.toml && touch ~/.config/alacritty/alacritty.toml"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-xresources"
name = "tinted-xresources"
themes-dir = "xresources"
hook = "cp -f %f ~/.Xresources.d/theme && xrdb -load ~/.Xresources"
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/base16-polybar"
name = "tinted-polybar"
themes-dir = "colors"
hook = "cp -f %f ~/.config/polybar/colors.ini"
supported-systems = ["base16"]

[[items]]
path = "https://github.com/tinted-theming/tinted-gowall"
name = "wallpaper"
themes-dir = "themes" 
supported-systems = ["base16", "base24"]

